# Generated by Django 5.1.6 on 2025-02-25 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("address", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="journey",
            name="route_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="end_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journeys_ending",
                to="core.location",
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="start_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journeys_starting",
                to="core.location",
            ),
        ),
        migrations.AlterField(
            model_name="reststop",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.location"
            ),
        ),
    ]
